AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target.

Parameters:
    VolumeName:
        Description: The name to be used for the EFS volume
        Type: String
        MinLength: '1'
        Default: myEFSvolume
    MountPoint:
        Description: The Linux mount point for the EFS volume
        Type: String
        MinLength: '1'
        Default: myEFSvolume

Resources:
    FileSystem:
        Type: AWS::EFS::FileSystem
        Properties:
          PerformanceMode: generalPurpose
          FileSystemTags:
          - Key: Name
            Value:
              Ref: VolumeName
    MountTarget:
        Type: AWS::EFS::MountTarget
        Properties:
            FileSystemId:
                Ref: FileSystem
            SubnetId:
                Ref: Subnet
            SecurityGroups:
            - Ref: MountTargetSecurityGroup